version: '3.9'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "developer"
      POSTGRES_PASSWORD: "developer"
      POSTGRES_DB: "quirby_dev_database"
    container_name: database
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 172.25.0.2

  quirby-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/api-teste
      - /api-teste/node_modules
    container_name: quirby
    links:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      backend:
        ipv4_address: 172.25.0.3

networks:
  backend:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
